name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: bert-classifier-server

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build -t alanyeungdev/bert-classifier-server:latest -t alanyeungdev/bert-classifier-server:${GITHUB_SHA::8} .

    - name: Docker Push
      run: docker push alanyeungdev/bert-classifier-server

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}      
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          docker login
          docker pull alanyeungdev/bert-classifier-server:${GITHUB_SHA::8}
