name: Update Serving Model

on: workflow_dispatch

#defaults:
#  run:
#    working-directory: bert-tf-serving

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
      
    - name: Copy model config
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_HOST_TF_SERVING }}
        username: ec2-user
        port: 22
        key: ${{ secrets.SSH_KEY_TF_SERVING }}
        source: "bert-tf-serving/models.config"
        target: "/home/ec2-user/model"
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master   
      with:
        host: ${{secrets.DEPLOYMENT_HOST_TF_SERVING}}
        username: ec2-user
        key: ${{ secrets.SSH_KEY_TF_SERVING }}
        port: 22
        envs: GITHUB_SHA
        script: |
          echo "Hi Hi"
