name: Update Serving Model

on: workflow_dispatch

defaults:
  run:
    working-directory: bert-tf-serving

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy model config
      uses: garygrossgarten/github-action-scp@release
      with:
        local: models.config
        remote: /home/ec2-user/model/models.config
        host: ${{ secrets.DEPLOYMENT_HOST_TF_SERVING }}
        username: ec2-user
        privateKey: ${{ secrets.SSH_KEY_TF_SERVING }}
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master   
      with:
        host: ${{secrets.DEPLOYMENT_HOST_TF_SERVING}}
        username: ec2-user
        key: ${{ secrets.SSH_KEY_TF_SERVING }}
        port: 22
        envs: GITHUB_SHA
        script: |
          echo "Hi Hi"
